import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'
import { backfillContentControls } from '../cms/content-backfill'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "redirects" ALTER COLUMN "status_code" SET DATA TYPE text;
  -- 301 is no longer offered (public routes can only emit 307/308); 308 has the same permanent semantics.
  UPDATE "redirects" SET "status_code" = '308' WHERE "status_code" = '301';
  ALTER TABLE "redirects" ALTER COLUMN "status_code" SET DEFAULT '308'::text;
  DROP TYPE "public"."enum_redirects_status_code";
  CREATE TYPE "public"."enum_redirects_status_code" AS ENUM('308', '307');
  ALTER TABLE "redirects" ALTER COLUMN "status_code" SET DEFAULT '308'::"public"."enum_redirects_status_code";
  ALTER TABLE "redirects" ALTER COLUMN "status_code" SET DATA TYPE "public"."enum_redirects_status_code" USING "status_code"::"public"."enum_redirects_status_code";
  ALTER TABLE "services_locales" ALTER COLUMN "problem_heading" SET DEFAULT 'Complexity should serve the business—not slow it down.';
  ALTER TABLE "services_locales" ALTER COLUMN "problem_description" SET DEFAULT 'Disconnected tools and inherited processes create duplicate work and unreliable decisions. We begin by understanding where the friction really lives: in the workflow, the data, or the interface between both.';
  ALTER TABLE "services_locales" ALTER COLUMN "deliverables_heading" SET DEFAULT 'A complete path from decision to working software.';
  ALTER TABLE "services_locales" ALTER COLUMN "process_heading" SET DEFAULT 'Senior attention, visible progress.';
  ALTER TABLE "services_locales" ALTER COLUMN "process_description" SET DEFAULT 'A focused cross-functional team works in short, transparent cycles. Every cycle produces something tangible to review, test, and improve—so important decisions happen with evidence.';
  ALTER TABLE "services_locales" ALTER COLUMN "next_heading" SET DEFAULT 'Start with the problem, not a feature list.';
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_problem_heading" SET DEFAULT 'Complexity should serve the business—not slow it down.';
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_problem_description" SET DEFAULT 'Disconnected tools and inherited processes create duplicate work and unreliable decisions. We begin by understanding where the friction really lives: in the workflow, the data, or the interface between both.';
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_deliverables_heading" SET DEFAULT 'A complete path from decision to working software.';
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_process_heading" SET DEFAULT 'Senior attention, visible progress.';
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_process_description" SET DEFAULT 'A focused cross-functional team works in short, transparent cycles. Every cycle produces something tangible to review, test, and improve—so important decisions happen with evidence.';
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_next_heading" SET DEFAULT 'Start with the problem, not a feature list.';
  ALTER TABLE "site_labels_locales" ALTER COLUMN "change_language" SET DEFAULT 'Switch to Arabic';
  ALTER TABLE "products_locales" ADD COLUMN "workflow_title" varchar;
  ALTER TABLE "_products_v_locales" ADD COLUMN "version_workflow_title" varchar;
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_direct_contact_label" varchar DEFAULT 'DIRECT CONTACT';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_project_tab" varchar DEFAULT 'Project inquiry';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_demo_tab" varchar DEFAULT 'Product demo';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_general_tab" varchar DEFAULT 'General inquiry';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_project_heading" varchar DEFAULT 'Tell us about the challenge.';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_demo_heading" varchar DEFAULT 'See the product in your workflow.';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_general_heading" varchar DEFAULT 'How can we help?';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_name_label" varchar DEFAULT 'Full name';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_name_placeholder" varchar DEFAULT 'Your name';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_email_label" varchar DEFAULT 'Work email';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_email_placeholder" varchar DEFAULT 'you@company.com';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_product_label" varchar DEFAULT 'Product';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_service_label" varchar DEFAULT 'What are you considering?';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_message_label" varchar DEFAULT 'Your message';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_message_placeholder" varchar DEFAULT 'A little context helps us prepare...';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_submit_label" varchar DEFAULT 'Send inquiry';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_status_label" varchar DEFAULT 'Submission status:';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_name_error" varchar DEFAULT 'Please add your name.';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_email_error" varchar DEFAULT 'Enter a valid work email.';
  ALTER TABLE "page_contact_locales" ADD COLUMN "form_message_error" varchar DEFAULT 'Tell us a little about what you need.';
  ALTER TABLE "listing_pages_locales" ADD COLUMN "services_card_note" varchar DEFAULT 'We map the real constraints, design for the people doing the work, and engineer for change.';
  ALTER TABLE "listing_pages_locales" ADD COLUMN "insights_section_label" varchar DEFAULT 'Our perspective';
  ALTER TABLE "listing_pages_locales" ADD COLUMN "insights_section_title" varchar DEFAULT 'Thinking for better digital work.';
  ALTER TABLE "site_labels" ADD COLUMN "article_cta_visible" boolean DEFAULT true;
  ALTER TABLE "site_labels" ADD COLUMN "article_cta_href" varchar DEFAULT '/contact';
  ALTER TABLE "site_labels_locales" ADD COLUMN "language_toggle" varchar DEFAULT 'العربية';
  ALTER TABLE "site_labels_locales" ADD COLUMN "main_navigation" varchar DEFAULT 'Main navigation';
  ALTER TABLE "site_labels_locales" ADD COLUMN "open_menu" varchar DEFAULT 'Open navigation';
  ALTER TABLE "site_labels_locales" ADD COLUMN "close_menu" varchar DEFAULT 'Close navigation';
  ALTER TABLE "site_labels_locales" ADD COLUMN "sector" varchar DEFAULT 'Sector';
  ALTER TABLE "site_labels_locales" ADD COLUMN "services" varchar DEFAULT 'Services';
  ALTER TABLE "site_labels_locales" ADD COLUMN "year" varchar DEFAULT 'Year';
  ALTER TABLE "site_labels_locales" ADD COLUMN "technology" varchar DEFAULT 'Technology';
  ALTER TABLE "site_labels_locales" ADD COLUMN "visit_client_site" varchar DEFAULT 'Visit client site';
  ALTER TABLE "site_labels_locales" ADD COLUMN "related_projects_label" varchar DEFAULT 'Related projects';
  ALTER TABLE "site_labels_locales" ADD COLUMN "related_projects_title" varchar DEFAULT 'Continue exploring';
  ALTER TABLE "site_labels_locales" ADD COLUMN "project_list" varchar DEFAULT 'Project list';
  ALTER TABLE "site_labels_locales" ADD COLUMN "filter_projects" varchar DEFAULT 'Filter projects';
  ALTER TABLE "site_labels_locales" ADD COLUMN "project_pages" varchar DEFAULT 'Project pages';
  ALTER TABLE "site_labels_locales" ADD COLUMN "draft_preview" varchar DEFAULT 'Draft preview';
  ALTER TABLE "site_labels_locales" ADD COLUMN "draft_preview_note" varchar DEFAULT 'Unpublished — visible to signed-in editors only.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "contents" varchar DEFAULT 'CONTENTS';
  ALTER TABLE "site_labels_locales" ADD COLUMN "more_insights_label" varchar DEFAULT 'MORE INSIGHTS';
  ALTER TABLE "site_labels_locales" ADD COLUMN "more_insights_title" varchar DEFAULT 'Thinking for better digital work.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "article_cta_eyebrow" varchar DEFAULT 'BUILDING AN OPERATIONAL PRODUCT?';
  ALTER TABLE "site_labels_locales" ADD COLUMN "article_cta_title" varchar DEFAULT 'We can help make the workflow clear.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "article_cta_label" varchar DEFAULT 'Talk to our team';
  ALTER TABLE "site_labels_locales" ADD COLUMN "service_kicker" varchar DEFAULT 'SERVICE';
  ALTER TABLE "site_labels_locales" ADD COLUMN "on_this_page" varchar DEFAULT 'ON THIS PAGE';
  ALTER TABLE "site_labels_locales" ADD COLUMN "problem_nav" varchar DEFAULT 'The problem';
  ALTER TABLE "site_labels_locales" ADD COLUMN "deliverables_nav" varchar DEFAULT 'Deliverables';
  ALTER TABLE "site_labels_locales" ADD COLUMN "process_nav" varchar DEFAULT 'Process';
  ALTER TABLE "site_labels_locales" ADD COLUMN "next_step_nav" varchar DEFAULT 'Next step';
  ALTER TABLE "site_labels_locales" ADD COLUMN "core_workflow" varchar DEFAULT 'CORE WORKFLOW';
  ALTER TABLE "site_labels_locales" ADD COLUMN "interface_tour" varchar DEFAULT 'INTERFACE TOUR';
  ALTER TABLE "site_labels_locales" ADD COLUMN "interface_tour_title" varchar DEFAULT 'The information you need. Nothing you don’t.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "faq" varchar DEFAULT 'FAQ';
  ALTER TABLE "site_labels_locales" ADD COLUMN "faq_title" varchar DEFAULT 'Questions, answered.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "not_found_eyebrow" varchar DEFAULT '404 / NOT FOUND';
  ALTER TABLE "site_labels_locales" ADD COLUMN "not_found_title" varchar DEFAULT 'This page isn’t here.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "not_found_body" varchar DEFAULT 'The address may have changed.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "not_found_link" varchar DEFAULT 'Return to Inheritix';
  ALTER TABLE "site_labels_locales" ADD COLUMN "error_eyebrow" varchar DEFAULT '500 / SERVICE ERROR';
  ALTER TABLE "site_labels_locales" ADD COLUMN "error_title" varchar DEFAULT 'This page couldn’t be loaded.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "error_body" varchar DEFAULT 'Something went wrong while fetching content. Please try again shortly.';
  ALTER TABLE "site_labels_locales" ADD COLUMN "error_retry" varchar DEFAULT 'Try again';`)

  // Store starter copy where the site previously relied on code fallbacks.
  await backfillContentControls({ payload, req })
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_redirects_status_code" ADD VALUE '301' BEFORE '307';
  ALTER TABLE "services_locales" ALTER COLUMN "problem_heading" DROP DEFAULT;
  ALTER TABLE "services_locales" ALTER COLUMN "problem_description" DROP DEFAULT;
  ALTER TABLE "services_locales" ALTER COLUMN "deliverables_heading" DROP DEFAULT;
  ALTER TABLE "services_locales" ALTER COLUMN "process_heading" DROP DEFAULT;
  ALTER TABLE "services_locales" ALTER COLUMN "process_description" DROP DEFAULT;
  ALTER TABLE "services_locales" ALTER COLUMN "next_heading" DROP DEFAULT;
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_problem_heading" DROP DEFAULT;
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_problem_description" DROP DEFAULT;
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_deliverables_heading" DROP DEFAULT;
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_process_heading" DROP DEFAULT;
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_process_description" DROP DEFAULT;
  ALTER TABLE "_services_v_locales" ALTER COLUMN "version_next_heading" DROP DEFAULT;
  ALTER TABLE "site_labels_locales" ALTER COLUMN "change_language" SET DEFAULT 'Change language';
  ALTER TABLE "products_locales" DROP COLUMN "workflow_title";
  ALTER TABLE "_products_v_locales" DROP COLUMN "version_workflow_title";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_direct_contact_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_project_tab";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_demo_tab";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_general_tab";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_project_heading";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_demo_heading";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_general_heading";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_name_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_name_placeholder";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_email_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_email_placeholder";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_product_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_service_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_message_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_message_placeholder";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_submit_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_status_label";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_name_error";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_email_error";
  ALTER TABLE "page_contact_locales" DROP COLUMN "form_message_error";
  ALTER TABLE "listing_pages_locales" DROP COLUMN "services_card_note";
  ALTER TABLE "listing_pages_locales" DROP COLUMN "insights_section_label";
  ALTER TABLE "listing_pages_locales" DROP COLUMN "insights_section_title";
  ALTER TABLE "site_labels" DROP COLUMN "article_cta_visible";
  ALTER TABLE "site_labels" DROP COLUMN "article_cta_href";
  ALTER TABLE "site_labels_locales" DROP COLUMN "language_toggle";
  ALTER TABLE "site_labels_locales" DROP COLUMN "main_navigation";
  ALTER TABLE "site_labels_locales" DROP COLUMN "open_menu";
  ALTER TABLE "site_labels_locales" DROP COLUMN "close_menu";
  ALTER TABLE "site_labels_locales" DROP COLUMN "sector";
  ALTER TABLE "site_labels_locales" DROP COLUMN "services";
  ALTER TABLE "site_labels_locales" DROP COLUMN "year";
  ALTER TABLE "site_labels_locales" DROP COLUMN "technology";
  ALTER TABLE "site_labels_locales" DROP COLUMN "visit_client_site";
  ALTER TABLE "site_labels_locales" DROP COLUMN "related_projects_label";
  ALTER TABLE "site_labels_locales" DROP COLUMN "related_projects_title";
  ALTER TABLE "site_labels_locales" DROP COLUMN "project_list";
  ALTER TABLE "site_labels_locales" DROP COLUMN "filter_projects";
  ALTER TABLE "site_labels_locales" DROP COLUMN "project_pages";
  ALTER TABLE "site_labels_locales" DROP COLUMN "draft_preview";
  ALTER TABLE "site_labels_locales" DROP COLUMN "draft_preview_note";
  ALTER TABLE "site_labels_locales" DROP COLUMN "contents";
  ALTER TABLE "site_labels_locales" DROP COLUMN "more_insights_label";
  ALTER TABLE "site_labels_locales" DROP COLUMN "more_insights_title";
  ALTER TABLE "site_labels_locales" DROP COLUMN "article_cta_eyebrow";
  ALTER TABLE "site_labels_locales" DROP COLUMN "article_cta_title";
  ALTER TABLE "site_labels_locales" DROP COLUMN "article_cta_label";
  ALTER TABLE "site_labels_locales" DROP COLUMN "service_kicker";
  ALTER TABLE "site_labels_locales" DROP COLUMN "on_this_page";
  ALTER TABLE "site_labels_locales" DROP COLUMN "problem_nav";
  ALTER TABLE "site_labels_locales" DROP COLUMN "deliverables_nav";
  ALTER TABLE "site_labels_locales" DROP COLUMN "process_nav";
  ALTER TABLE "site_labels_locales" DROP COLUMN "next_step_nav";
  ALTER TABLE "site_labels_locales" DROP COLUMN "core_workflow";
  ALTER TABLE "site_labels_locales" DROP COLUMN "interface_tour";
  ALTER TABLE "site_labels_locales" DROP COLUMN "interface_tour_title";
  ALTER TABLE "site_labels_locales" DROP COLUMN "faq";
  ALTER TABLE "site_labels_locales" DROP COLUMN "faq_title";
  ALTER TABLE "site_labels_locales" DROP COLUMN "not_found_eyebrow";
  ALTER TABLE "site_labels_locales" DROP COLUMN "not_found_title";
  ALTER TABLE "site_labels_locales" DROP COLUMN "not_found_body";
  ALTER TABLE "site_labels_locales" DROP COLUMN "not_found_link";
  ALTER TABLE "site_labels_locales" DROP COLUMN "error_eyebrow";
  ALTER TABLE "site_labels_locales" DROP COLUMN "error_title";
  ALTER TABLE "site_labels_locales" DROP COLUMN "error_body";
  ALTER TABLE "site_labels_locales" DROP COLUMN "error_retry";`)
}
