/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    clients: Client;
    projects: Project;
    products: Product;
    services: Service;
    posts: Post;
    categories: Category;
    authors: Author;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'page-home': PageHome;
    'page-about': PageAbout;
    'page-contact': PageContact;
    'listing-pages': ListingPage;
    'site-labels': SiteLabel;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'page-home': PageHomeSelect<false> | PageHomeSelect<true>;
    'page-about': PageAboutSelect<false> | PageAboutSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
    'listing-pages': ListingPagesSelect<false> | ListingPagesSelect<true>;
    'site-labels': SiteLabelsSelect<false> | SiteLabelsSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  /**
   * Set automatically when an account was found using a published default password. Cleared when a new password is saved.
   */
  passwordRotationRequired?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Meaningful screen reader description in English and Arabic.
   */
  alt: string;
  /**
   * Detailed description of the asset for editorial use.
   */
  description?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Localized description of the client's mark or logo.
   */
  logoDescription: string;
  /**
   * Optional client website (e.g. https://example.com).
   */
  website?: string | null;
  /**
   * Original brand colors are preserved by default as requested.
   */
  displayMode?: ('original' | 'monochrome') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * URL segment, lowercase-with-hyphens. Changing the slug of a published record creates a permanent redirect when the change is published.
   */
  slug: string;
  title: string;
  /**
   * Client organization for this project.
   */
  client: number | Client;
  /**
   * Short summary shown on project cards.
   */
  summary: string;
  /**
   * Introduction displayed in the project hero.
   */
  intro?: string | null;
  /**
   * Industry / sector (e.g. Enterprise operations, Logistics, Hospitality).
   */
  sector: string;
  year: string;
  services: {
    name: string;
    id?: string | null;
  }[];
  techStack?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Project card cover image.
   */
  cardImage: number | Media;
  /**
   * Hero visual displayed at the top of the detail page.
   */
  heroImage: number | Media;
  /**
   * Feature this project on the homepage.
   */
  featured?: boolean | null;
  /**
   * Display ordering priority (lower numbers appear first).
   */
  displayOrder?: number | null;
  /**
   * Reorderable external links (e.g. live product, case publication).
   */
  externalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Modular story blocks (intro, metrics, rich text, images, quote, cta).
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'metrics';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading: string;
            body?: string | null;
            actionLabel: string;
            actionHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Related projects shown at the bottom of the page, in this order. Unpublished selections are skipped on the public site.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * History of previously published slugs.
   */
  previousSlugs?:
    | {
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Search and social metadata. Leave blank to use the page content and the site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * URL segment, lowercase-with-hyphens. Changing the slug of a published record creates a permanent redirect when the change is published.
   */
  slug: string;
  name: string;
  /**
   * Eyebrow tag (e.g. 01 / LOGISTICS OPERATIONS).
   */
  badge: string;
  category: string;
  tagline: string;
  summary: string;
  heroHeadline: string;
  heroDescription: string;
  /**
   * Copy for the homepage 'Our products' section. Falls back to the summary.
   */
  homeDescription?: string | null;
  visualType?: ('dashboard' | 'phone') | null;
  valuePoints?:
    | {
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  workflowSteps?:
    | {
        stepNumber: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Heading of the core workflow section. Leave empty to hide the heading.
   */
  workflowTitle?: string | null;
  tourTitle?: string | null;
  tourDescription?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  /**
   * Search and social metadata. Leave blank to use the page content and the site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  number: string;
  /**
   * URL segment, lowercase-with-hyphens. Changing the slug of a published record creates a permanent redirect when the change is published.
   */
  slug: string;
  title: string;
  shortDescription: string;
  heroIntro?: string | null;
  problemEyebrow?: string | null;
  problemHeading?: string | null;
  problemDescription?: string | null;
  deliverablesEyebrow?: string | null;
  deliverablesHeading?: string | null;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  processEyebrow?: string | null;
  processHeading?: string | null;
  processDescription?: string | null;
  nextEyebrow?: string | null;
  nextHeading?: string | null;
  displayOrder?: number | null;
  /**
   * Search and social metadata. Leave blank to use the page content and the site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment, lowercase-with-hyphens. Changing the slug of a published record creates a permanent redirect when the change is published.
   */
  slug: string;
  category?: (number | null) | Category;
  /**
   * Display category label (e.g. PRODUCT THINKING, AI & AUTOMATION, DESIGN).
   */
  categoryLabel?: string | null;
  author?: (number | null) | Author;
  publishedAt?: string | null;
  readTime?: string | null;
  color?: ('ink' | 'blue' | 'cyan') | null;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  coverLabel?: string | null;
  coverSubtext?: string | null;
  coverCaption?: string | null;
  leadParagraph?: string | null;
  /**
   * Article body. Each section appears in the on-page table of contents.
   */
  sections?:
    | {
        /**
         * Anchor ID for on-page table of contents (e.g. friction, workflow).
         */
        sectionId?: string | null;
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        quote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Search and social metadata. Leave blank to use the page content and the site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Avatar badge text (e.g. IN).
   */
  initials?: string | null;
  role?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Old public path, e.g. /projects/old-slug
   */
  from: string;
  /**
   * Destination path (/new-path) or absolute https:// URL.
   */
  to: string;
  /**
   * 308 for moved content (search engines transfer ranking), 307 for temporary moves.
   */
  statusCode: '308' | '307';
  source?: ('manual' | 'slug-change') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  passwordRotationRequired?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  description?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoDescription?: T;
  website?: T;
  displayMode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  client?: T;
  summary?: T;
  intro?: T;
  sector?: T;
  year?: T;
  services?:
    | T
    | {
        name?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  cardImage?: T;
  heroImage?: T;
  featured?: T;
  displayOrder?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        intro?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              actionLabel?: T;
              actionHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedProjects?: T;
  previousSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  badge?: T;
  category?: T;
  tagline?: T;
  summary?: T;
  heroHeadline?: T;
  heroDescription?: T;
  homeDescription?: T;
  visualType?: T;
  valuePoints?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  workflowSteps?:
    | T
    | {
        stepNumber?: T;
        name?: T;
        id?: T;
      };
  workflowTitle?: T;
  tourTitle?: T;
  tourDescription?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  number?: T;
  slug?: T;
  title?: T;
  shortDescription?: T;
  heroIntro?: T;
  problemEyebrow?: T;
  problemHeading?: T;
  problemDescription?: T;
  deliverablesEyebrow?: T;
  deliverablesHeading?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  processEyebrow?: T;
  processHeading?: T;
  processDescription?: T;
  nextEyebrow?: T;
  nextHeading?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  categoryLabel?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  color?: T;
  excerpt?: T;
  coverImage?: T;
  coverLabel?: T;
  coverSubtext?: T;
  coverCaption?: T;
  leadParagraph?: T;
  sections?:
    | T
    | {
        sectionId?: T;
        heading?: T;
        body?: T;
        quote?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  initials?: T;
  role?: T;
  avatar?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Logos and favicon used in the website header, footer and browser tab.
   */
  branding?: {
    /**
     * Header logo on light background (SVG or PNG). Falls back to the INHERITIX mark.
     */
    logo?: (number | null) | Media;
    /**
     * Footer logo on dark background. Falls back to the header logo.
     */
    logoLight?: (number | null) | Media;
    /**
     * Square PNG or SVG, at least 48×48.
     */
    favicon?: (number | null) | Media;
  };
  /**
   * Validated brand colors applied to the website design tokens. Defaults match the approved design.
   */
  brandColors?: {
    /**
     * Primary blue (--blue): links, active navigation, accent headline.
     */
    primary?: string | null;
    /**
     * Accent cyan (--cyan): highlights, focus rings, progress bar.
     */
    accent?: string | null;
    /**
     * Ink navy (--navy): body text, dark sections, buttons.
     */
    dark?: string | null;
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerHeading?: string | null;
  footerInvitation?: string | null;
  footerCtaLabel?: string | null;
  copyright?: string | null;
  location?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items: {
    label: string;
    /**
     * English path; the Arabic site prefixes /ar automatically.
     */
    href: string;
    id?: string | null;
  }[];
  headerCta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home".
 */
export interface PageHome {
  id: number;
  heroIndex?: string | null;
  heroTitleA: string;
  heroTitleB: string;
  heroCopy: string;
  heroPrimaryCta?: {
    label?: string | null;
    /**
     * Site paths are automatically prefixed with /ar on the Arabic site.
     */
    href?: string | null;
  };
  heroSecondaryCta?: {
    label?: string | null;
    /**
     * Site paths are automatically prefixed with /ar on the Arabic site.
     */
    href?: string | null;
  };
  /**
   * Drag to reorder homepage sections. Sections missing from this list are appended in the default order. Use each section's Visible toggle to hide it.
   */
  sectionOrder?:
    | {
        section: 'showcase' | 'selectedWork' | 'capabilities' | 'products' | 'approach' | 'perspective' | 'insights';
        id?: string | null;
      }[]
    | null;
  showcaseSection?: {
    /**
     * Show this section for the selected locale.
     */
    visible?: boolean | null;
    stageLabel?: string | null;
    stageNote?: string | null;
  };
  selectedWorkSection?: {
    /**
     * Show this section for the selected locale.
     */
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
    /**
     * Large feature card (name, summary and mockup come from the product).
     */
    featuredProduct?: (number | null) | Product;
    featuredEyebrow?: string | null;
    /**
     * Smaller product card.
     */
    secondaryProduct?: (number | null) | Product;
    secondaryEyebrow?: string | null;
    productCtaLabel?: string | null;
    /**
     * Capability story card next to the product card.
     */
    storyCard?: {
      /**
       * Show this story card for the selected locale.
       */
      visible?: boolean | null;
      /**
       * “Featured project” shows the first published project marked Featured (by display order), falling back to the manual copy when none exists.
       */
      source?: ('manual' | 'featuredProject') | null;
      visualIndex?: string | null;
      visualText?: string | null;
      eyebrow?: string | null;
      title?: string | null;
      description?: string | null;
      cta?: {
        label?: string | null;
        /**
         * Site paths are automatically prefixed with /ar on the Arabic site.
         */
        href?: string | null;
      };
    };
  };
  capabilitiesSection?: {
    /**
     * Show this section for the selected locale.
     */
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
  };
  productsDarkSection?: {
    /**
     * Show this section for the selected locale.
     */
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
    /**
     * Button text before the product name, e.g. “Explore LOGISTTEX”.
     */
    ctaPrefix?: string | null;
  };
  approachSection?: {
    /**
     * Show this section for the selected locale.
     */
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
    phases?:
      | {
          number: string;
          name: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  perspectiveSection?: {
    /**
     * Show this section for the selected locale.
     */
    visible?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    cta?: {
      label?: string | null;
      /**
       * Site paths are automatically prefixed with /ar on the Arabic site.
       */
      href?: string | null;
    };
    /**
     * Uploaded image (preferred). Its localized alt text is used.
     */
    image?: (number | null) | Media;
    /**
     * Fallback external image when no upload is selected.
     */
    imageUrl?: string | null;
    /**
     * Alt text for the fallback external image.
     */
    imageAlt?: string | null;
  };
  insightsSection?: {
    /**
     * Show this section for the selected locale.
     */
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
  };
  /**
   * Search and social metadata. Leave blank to use the page content and the site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about".
 */
export interface PageAbout {
  id: number;
  kicker?: string | null;
  title: string;
  intro: string;
  /**
   * Uploaded hero image (preferred). Its localized alt text is used.
   */
  image?: (number | null) | Media;
  /**
   * Alt text for the fallback external image.
   */
  imageAlt?: string | null;
  imageUrl?: string | null;
  manifestoEyebrow?: string | null;
  manifestoTitle?: string | null;
  manifestoParagraphOne?: string | null;
  manifestoParagraphTwo?: string | null;
  principles?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search and social metadata. Leave blank to use the page content and the site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: number;
  kicker?: string | null;
  title: string;
  intro: string;
  directEmail?: string | null;
  directNote?: string | null;
  /**
   * Truthful boundary notice regarding form submissions in Milestone Two.
   */
  boundaryNotice?: string | null;
  /**
   * Contact form copy. Product and service choices come from published Products and Services. Submission handling arrives in Milestone Three.
   */
  form?: {
    directContactLabel?: string | null;
    projectTab?: string | null;
    demoTab?: string | null;
    generalTab?: string | null;
    projectHeading?: string | null;
    demoHeading?: string | null;
    generalHeading?: string | null;
    nameLabel?: string | null;
    namePlaceholder?: string | null;
    emailLabel?: string | null;
    emailPlaceholder?: string | null;
    productLabel?: string | null;
    serviceLabel?: string | null;
    messageLabel?: string | null;
    messagePlaceholder?: string | null;
    submitLabel?: string | null;
    statusLabel?: string | null;
    nameError?: string | null;
    emailError?: string | null;
    messageError?: string | null;
  };
  /**
   * Search and social metadata. Leave blank to use the page content and the site defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages".
 */
export interface ListingPage {
  id: number;
  services?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
    /**
     * Sentence appended to every service card. Leave empty to show only the service description.
     */
    cardNote?: string | null;
    /**
     * Search and social metadata. Leave blank to use the page content and the site defaults.
     */
    seo?: {
      title?: string | null;
      description?: string | null;
      /**
       * Social sharing image (1200×630 recommended).
       */
      ogImage?: (number | null) | Media;
      /**
       * Hide this page from search engines and the sitemap.
       */
      noIndex?: boolean | null;
    };
  };
  products?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
    /**
     * Search and social metadata. Leave blank to use the page content and the site defaults.
     */
    seo?: {
      title?: string | null;
      description?: string | null;
      /**
       * Social sharing image (1200×630 recommended).
       */
      ogImage?: (number | null) | Media;
      /**
       * Hide this page from search engines and the sitemap.
       */
      noIndex?: boolean | null;
    };
  };
  projects?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
    /**
     * Search and social metadata. Leave blank to use the page content and the site defaults.
     */
    seo?: {
      title?: string | null;
      description?: string | null;
      /**
       * Social sharing image (1200×630 recommended).
       */
      ogImage?: (number | null) | Media;
      /**
       * Hide this page from search engines and the sitemap.
       */
      noIndex?: boolean | null;
    };
  };
  insights?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
    sectionLabel?: string | null;
    sectionTitle?: string | null;
    /**
     * Search and social metadata. Leave blank to use the page content and the site defaults.
     */
    seo?: {
      title?: string | null;
      description?: string | null;
      /**
       * Social sharing image (1200×630 recommended).
       */
      ogImage?: (number | null) | Media;
      /**
       * Hide this page from search engines and the sitemap.
       */
      noIndex?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shared visitor-facing labels. Clearing a label hides that element on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-labels".
 */
export interface SiteLabel {
  id: number;
  exploreWork?: string | null;
  startProject?: string | null;
  viewProduct?: string | null;
  viewProject?: string | null;
  /**
   * Prefix for product links, e.g. “Explore LOGISTTEX”.
   */
  explore?: string | null;
  readStory?: string | null;
  seeService?: string | null;
  requestDemo?: string | null;
  discussProject?: string | null;
  allProjects?: string | null;
  previousPage?: string | null;
  nextPage?: string | null;
  backToTop?: string | null;
  skipToContent?: string | null;
  /**
   * Screen-reader label of the language switch.
   */
  changeLanguage?: string | null;
  /**
   * Visible text of the language switch (e.g. العربية on English pages, EN on Arabic pages).
   */
  languageToggle?: string | null;
  mainNavigation?: string | null;
  openMenu?: string | null;
  closeMenu?: string | null;
  sector?: string | null;
  services?: string | null;
  year?: string | null;
  technology?: string | null;
  visitClientSite?: string | null;
  relatedProjectsLabel?: string | null;
  relatedProjectsTitle?: string | null;
  /**
   * Screen-reader heading of the project grid.
   */
  projectList?: string | null;
  /**
   * Screen-reader label of the sector filter.
   */
  filterProjects?: string | null;
  /**
   * Screen-reader label of the pagination.
   */
  projectPages?: string | null;
  /**
   * Shown to signed-in editors on unpublished previews.
   */
  draftPreview?: string | null;
  draftPreviewNote?: string | null;
  contents?: string | null;
  moreInsightsLabel?: string | null;
  moreInsightsTitle?: string | null;
  articleCta?: {
    /**
     * Show the article call to action for the selected locale.
     */
    visible?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    label?: string | null;
    /**
     * Site path; /ar is added automatically on Arabic pages.
     */
    href?: string | null;
  };
  /**
   * Shown before the service number, e.g. “SERVICE 01”.
   */
  serviceKicker?: string | null;
  onThisPage?: string | null;
  problemNav?: string | null;
  deliverablesNav?: string | null;
  processNav?: string | null;
  nextStepNav?: string | null;
  coreWorkflow?: string | null;
  interfaceTour?: string | null;
  interfaceTourTitle?: string | null;
  faq?: string | null;
  faqTitle?: string | null;
  notFoundEyebrow?: string | null;
  notFoundTitle?: string | null;
  notFoundBody?: string | null;
  notFoundLink?: string | null;
  errorEyebrow?: string | null;
  errorTitle?: string | null;
  errorBody?: string | null;
  errorRetry?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  branding?:
    | T
    | {
        logo?: T;
        logoLight?: T;
        favicon?: T;
      };
  brandColors?:
    | T
    | {
        primary?: T;
        accent?: T;
        dark?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerHeading?: T;
  footerInvitation?: T;
  footerCtaLabel?: T;
  copyright?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home_select".
 */
export interface PageHomeSelect<T extends boolean = true> {
  heroIndex?: T;
  heroTitleA?: T;
  heroTitleB?: T;
  heroCopy?: T;
  heroPrimaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  sectionOrder?:
    | T
    | {
        section?: T;
        id?: T;
      };
  showcaseSection?:
    | T
    | {
        visible?: T;
        stageLabel?: T;
        stageNote?: T;
      };
  selectedWorkSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
        featuredProduct?: T;
        featuredEyebrow?: T;
        secondaryProduct?: T;
        secondaryEyebrow?: T;
        productCtaLabel?: T;
        storyCard?:
          | T
          | {
              visible?: T;
              source?: T;
              visualIndex?: T;
              visualText?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
            };
      };
  capabilitiesSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
      };
  productsDarkSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
        ctaPrefix?: T;
      };
  approachSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
        phases?:
          | T
          | {
              number?: T;
              name?: T;
              description?: T;
              id?: T;
            };
      };
  perspectiveSection?:
    | T
    | {
        visible?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
        imageUrl?: T;
        imageAlt?: T;
      };
  insightsSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about_select".
 */
export interface PageAboutSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  intro?: T;
  image?: T;
  imageAlt?: T;
  imageUrl?: T;
  manifestoEyebrow?: T;
  manifestoTitle?: T;
  manifestoParagraphOne?: T;
  manifestoParagraphTwo?: T;
  principles?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  intro?: T;
  directEmail?: T;
  directNote?: T;
  boundaryNotice?: T;
  form?:
    | T
    | {
        directContactLabel?: T;
        projectTab?: T;
        demoTab?: T;
        generalTab?: T;
        projectHeading?: T;
        demoHeading?: T;
        generalHeading?: T;
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        productLabel?: T;
        serviceLabel?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        statusLabel?: T;
        nameError?: T;
        emailError?: T;
        messageError?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages_select".
 */
export interface ListingPagesSelect<T extends boolean = true> {
  services?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
        cardNote?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              ogImage?: T;
              noIndex?: T;
            };
      };
  products?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              ogImage?: T;
              noIndex?: T;
            };
      };
  projects?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              ogImage?: T;
              noIndex?: T;
            };
      };
  insights?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
        sectionLabel?: T;
        sectionTitle?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              ogImage?: T;
              noIndex?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-labels_select".
 */
export interface SiteLabelsSelect<T extends boolean = true> {
  exploreWork?: T;
  startProject?: T;
  viewProduct?: T;
  viewProject?: T;
  explore?: T;
  readStory?: T;
  seeService?: T;
  requestDemo?: T;
  discussProject?: T;
  allProjects?: T;
  previousPage?: T;
  nextPage?: T;
  backToTop?: T;
  skipToContent?: T;
  changeLanguage?: T;
  languageToggle?: T;
  mainNavigation?: T;
  openMenu?: T;
  closeMenu?: T;
  sector?: T;
  services?: T;
  year?: T;
  technology?: T;
  visitClientSite?: T;
  relatedProjectsLabel?: T;
  relatedProjectsTitle?: T;
  projectList?: T;
  filterProjects?: T;
  projectPages?: T;
  draftPreview?: T;
  draftPreviewNote?: T;
  contents?: T;
  moreInsightsLabel?: T;
  moreInsightsTitle?: T;
  articleCta?:
    | T
    | {
        visible?: T;
        eyebrow?: T;
        title?: T;
        label?: T;
        href?: T;
      };
  serviceKicker?: T;
  onThisPage?: T;
  problemNav?: T;
  deliverablesNav?: T;
  processNav?: T;
  nextStepNav?: T;
  coreWorkflow?: T;
  interfaceTour?: T;
  interfaceTourTitle?: T;
  faq?: T;
  faqTitle?: T;
  notFoundEyebrow?: T;
  notFoundTitle?: T;
  notFoundBody?: T;
  notFoundLink?: T;
  errorEyebrow?: T;
  errorTitle?: T;
  errorBody?: T;
  errorRetry?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}