/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    clients: Client;
    projects: Project;
    products: Product;
    services: Service;
    posts: Post;
    categories: Category;
    authors: Author;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'page-home': PageHome;
    'page-about': PageAbout;
    'page-contact': PageContact;
    'listing-pages': ListingPage;
    'site-labels': SiteLabel;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'page-home': PageHomeSelect<false> | PageHomeSelect<true>;
    'page-about': PageAboutSelect<false> | PageAboutSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
    'listing-pages': ListingPagesSelect<false> | ListingPagesSelect<true>;
    'site-labels': SiteLabelsSelect<false> | SiteLabelsSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Meaningful screen reader description in English and Arabic.
   */
  alt: string;
  /**
   * Detailed description of the asset for editorial use.
   */
  description?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Localized description of the client's mark or logo.
   */
  logoDescription: string;
  /**
   * Optional client website (e.g. https://example.com).
   */
  website?: string | null;
  /**
   * Original brand colors are preserved by default as requested.
   */
  displayMode?: ('original' | 'monochrome') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * URL slug for this project (e.g. logistics-control-system).
   */
  slug: string;
  title: string;
  /**
   * Client organization for this project.
   */
  client: number | Client;
  /**
   * Short summary shown on project cards.
   */
  summary: string;
  /**
   * Introduction displayed in the project hero.
   */
  intro?: string | null;
  /**
   * Industry / sector (e.g. Enterprise operations, Logistics, Hospitality).
   */
  sector: string;
  year: string;
  services: {
    name: string;
    id?: string | null;
  }[];
  techStack?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Project card cover image.
   */
  cardImage: number | Media;
  /**
   * Hero visual displayed at the top of the detail page.
   */
  heroImage: number | Media;
  /**
   * Feature this project on the homepage.
   */
  featured?: boolean | null;
  /**
   * Display ordering priority (lower numbers appear first).
   */
  displayOrder?: number | null;
  /**
   * Reorderable external links (e.g. live product, case publication).
   */
  externalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Modular story blocks (intro, metrics, rich text, images, quote, cta).
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'metrics';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading: string;
            body?: string | null;
            actionLabel: string;
            actionHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Related projects displayed at the bottom of the page.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * History of previously published slugs.
   */
  previousSlugs?:
    | {
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  slug: string;
  name: string;
  /**
   * Eyebrow tag (e.g. 01 / LOGISTICS OPERATIONS).
   */
  badge: string;
  category: string;
  tagline: string;
  summary: string;
  heroHeadline: string;
  heroDescription: string;
  visualType?: ('dashboard' | 'phone') | null;
  valuePoints?:
    | {
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  workflowSteps?:
    | {
        stepNumber: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  tourTitle?: string | null;
  tourDescription?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  number: string;
  slug: string;
  title: string;
  shortDescription: string;
  heroIntro?: string | null;
  problemEyebrow?: string | null;
  problemHeading?: string | null;
  problemDescription?: string | null;
  deliverablesEyebrow?: string | null;
  deliverablesHeading?: string | null;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  processEyebrow?: string | null;
  processHeading?: string | null;
  processDescription?: string | null;
  nextEyebrow?: string | null;
  nextHeading?: string | null;
  displayOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  category?: (number | null) | Category;
  /**
   * Display category label (e.g. PRODUCT THINKING, AI & AUTOMATION, DESIGN).
   */
  categoryLabel?: string | null;
  author?: (number | null) | Author;
  publishedAt?: string | null;
  readTime?: string | null;
  color?: ('ink' | 'blue' | 'cyan') | null;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  coverLabel?: string | null;
  coverSubtext?: string | null;
  coverCaption?: string | null;
  leadParagraph?: string | null;
  sections?:
    | {
        /**
         * Anchor ID for on-page table of contents (e.g. friction, workflow).
         */
        sectionId?: string | null;
        heading: string;
        body: string;
        quote?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Avatar badge text (e.g. IN).
   */
  initials?: string | null;
  role?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  statusCode?: ('308' | '301' | '307') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  description?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoDescription?: T;
  website?: T;
  displayMode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  client?: T;
  summary?: T;
  intro?: T;
  sector?: T;
  year?: T;
  services?:
    | T
    | {
        name?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  cardImage?: T;
  heroImage?: T;
  featured?: T;
  displayOrder?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        intro?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              actionLabel?: T;
              actionHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedProjects?: T;
  previousSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  badge?: T;
  category?: T;
  tagline?: T;
  summary?: T;
  heroHeadline?: T;
  heroDescription?: T;
  visualType?: T;
  valuePoints?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  workflowSteps?:
    | T
    | {
        stepNumber?: T;
        name?: T;
        id?: T;
      };
  tourTitle?: T;
  tourDescription?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  number?: T;
  slug?: T;
  title?: T;
  shortDescription?: T;
  heroIntro?: T;
  problemEyebrow?: T;
  problemHeading?: T;
  problemDescription?: T;
  deliverablesEyebrow?: T;
  deliverablesHeading?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  processEyebrow?: T;
  processHeading?: T;
  processDescription?: T;
  nextEyebrow?: T;
  nextHeading?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  categoryLabel?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  color?: T;
  excerpt?: T;
  coverImage?: T;
  coverLabel?: T;
  coverSubtext?: T;
  coverCaption?: T;
  leadParagraph?: T;
  sections?:
    | T
    | {
        sectionId?: T;
        heading?: T;
        body?: T;
        quote?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  initials?: T;
  role?: T;
  avatar?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Validated brand colors used across UI accents.
   */
  brandColors?: {
    primary?: string | null;
    accent?: string | null;
    dark?: string | null;
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerHeading?: string | null;
  footerInvitation?: string | null;
  footerCtaLabel?: string | null;
  copyright?: string | null;
  location?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  headerCta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home".
 */
export interface PageHome {
  id: number;
  heroIndex?: string | null;
  heroTitleA: string;
  heroTitleB: string;
  heroCopy: string;
  heroPrimaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  heroSecondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  showcaseSection?: {
    visible?: boolean | null;
    stageLabel?: string | null;
    stageNote?: string | null;
  };
  selectedWorkSection?: {
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
  };
  capabilitiesSection?: {
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
  };
  productsDarkSection?: {
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
  };
  approachSection?: {
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
    phases?:
      | {
          number: string;
          name: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  perspectiveSection?: {
    visible?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    imageUrl?: string | null;
  };
  insightsSection?: {
    visible?: boolean | null;
    label?: string | null;
    title?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about".
 */
export interface PageAbout {
  id: number;
  kicker?: string | null;
  title: string;
  intro: string;
  imageUrl?: string | null;
  manifestoEyebrow?: string | null;
  manifestoTitle?: string | null;
  manifestoParagraphOne?: string | null;
  manifestoParagraphTwo?: string | null;
  principles?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: number;
  kicker?: string | null;
  title: string;
  intro: string;
  directEmail?: string | null;
  directNote?: string | null;
  /**
   * Truthful boundary notice regarding form submissions in Milestone Two.
   */
  boundaryNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages".
 */
export interface ListingPage {
  id: number;
  services?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  products?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  projects?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  insights?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-labels".
 */
export interface SiteLabel {
  id: number;
  exploreWork?: string | null;
  startProject?: string | null;
  viewProduct?: string | null;
  readStory?: string | null;
  seeService?: string | null;
  requestDemo?: string | null;
  discussProject?: string | null;
  allProjects?: string | null;
  previousPage?: string | null;
  nextPage?: string | null;
  backToTop?: string | null;
  skipToContent?: string | null;
  changeLanguage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  brandColors?:
    | T
    | {
        primary?: T;
        accent?: T;
        dark?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerHeading?: T;
  footerInvitation?: T;
  footerCtaLabel?: T;
  copyright?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home_select".
 */
export interface PageHomeSelect<T extends boolean = true> {
  heroIndex?: T;
  heroTitleA?: T;
  heroTitleB?: T;
  heroCopy?: T;
  heroPrimaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  showcaseSection?:
    | T
    | {
        visible?: T;
        stageLabel?: T;
        stageNote?: T;
      };
  selectedWorkSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
      };
  capabilitiesSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
      };
  productsDarkSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
      };
  approachSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
        phases?:
          | T
          | {
              number?: T;
              name?: T;
              description?: T;
              id?: T;
            };
      };
  perspectiveSection?:
    | T
    | {
        visible?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        imageUrl?: T;
      };
  insightsSection?:
    | T
    | {
        visible?: T;
        label?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about_select".
 */
export interface PageAboutSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  intro?: T;
  imageUrl?: T;
  manifestoEyebrow?: T;
  manifestoTitle?: T;
  manifestoParagraphOne?: T;
  manifestoParagraphTwo?: T;
  principles?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  intro?: T;
  directEmail?: T;
  directNote?: T;
  boundaryNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages_select".
 */
export interface ListingPagesSelect<T extends boolean = true> {
  services?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
      };
  products?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
      };
  projects?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
      };
  insights?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-labels_select".
 */
export interface SiteLabelsSelect<T extends boolean = true> {
  exploreWork?: T;
  startProject?: T;
  viewProduct?: T;
  readStory?: T;
  seeService?: T;
  requestDemo?: T;
  discussProject?: T;
  allProjects?: T;
  previousPage?: T;
  nextPage?: T;
  backToTop?: T;
  skipToContent?: T;
  changeLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}